services:
  proxy:
    image: nginx:latest
    container_name: 	diamond-body-art-proxy
    ports:
      - ":80"
      - ":443"
    links:
      - ghostblog
    volumes:
      - $PWD/nginx/diamondbodyart.molovestoshare.com.crt:/etc/ssl/certs/diamondbodyart.molovestoshare.com.crt:z
      - $PWD/nginx/diamondbodyart.molovestoshare.com.key:/etc/ssl/private/diamondbodyart.molovestoshare.com.pem:z
      - $PWD/nginx/ghost.conf:/etc/nginx/sites-enabled/ghost.conf:z
  ghostblog:
    image: ghost:latest
    container_name: diamond-body-art-website
    hostname: dba-ghostblog
    restart: always
    ports:
      - 23686:2368
    depends_on:
      - ghostdb
    environment:
      url: https://diamondbodyart.molovestoshare.com/
      database__client: mysql
      database__connection__host: dba-ghostdb # ghostdb
      database__connection__user: ghost
      database__connection__password: ghostdbpass
      database__connection__database: ghostdb
    volumes:
      - /data/compose/dbaghost/content:/var/lib/ghost/content

  ghostdb:
    image: mariadb:latest
    container_name: diamond-body-art-database
    hostname: dba-ghostdb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_mysql_root_password
      MYSQL_USER: ghost
      MYSQL_PASSWORD: ghostdbpass
      MYSQL_DATABASE: ghostdb
    volumes:
      - /data/compose/dbaghost/mysql:/var/lib/mysql