global:
  scrape_interval:     15s
  evaluation_interval: 15s

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
      monitor: 'monitoring-stack'

# Load and evaluate rules in this file every 'evaluation_interval' seconds.
rule_files:
  - "alert.rules"

# Load and evaluate rules over on https://prometheus-us-central1.grafana.net/api/prom.
# remote_write:
# - url: https://prometheus-us-central1.grafana.net/api/prom/push
  # basic_auth:
    # username: "979191"
    # password: eyJrIjoiNzc5YjE1ZDg2YTZhNmM3NGNjNmMyY2FiZDk5MWQ3YTI5YmJlNWU2YyIsIm4iOiJtb21vdGhlaG9ibzIxMCIsImlkIjo4NTIxOTB9

# A scrape configuration containing exactly one endpoint to scrape.
scrape_configs:
  - job_name: 'nodeexporter'
    scrape_interval: 5s
    static_configs:
      - targets: ['nodeexporter:9100']

  - job_name: 'cadvisor'
    scrape_interval: 5s
    static_configs:
      - targets: ['cadvisor:8080']

  - job_name: 'prometheus'
    scrape_interval: 10s
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'pushgateway'
    scrape_interval: 10s
    honor_labels: true
    static_configs:
      - targets: ['pushgateway:9091']

  - job_name: 'netdata'
    metrics_path: '/api/v1/allmetrics'
    params:
      format: [ prometheus_all_hosts ]
    honor_labels: true
    static_configs:
      - targets: ['netdata:19999']

  - job_name: 'healthchecks-mauricenash1gmailcom'
    scheme: https
    metrics_path: /projects/8eeea913-83fc-4b52-99f9-55e1a3b9d33d/metrics/ZjXGELuU8zHCwfIzVUfmXL9CP4LF3qNf
    static_configs:
    - targets: ['healthchecks.io']

  # - job_name: watchtower
  #   scrape_interval: 5s
  #   metrics_path: /v1/metrics
  #   bearer_token: demotoken
  #   static_configs:
  #     - targets: [':8080']

alerting:
  alertmanagers:
  - scheme: http
    static_configs:
    - targets: 
      - 'alertmanager:9093'
