---
version: "2.1"
volumes:
  container_data: {}
services:
  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
      - VERSION=docker
      - PLEX_CLAIM= #optional
    volumes:
      - container_data:/config
      - /home/monash/Backup_Disk/media/tv:/tv
      - /home/monash/Backup_Disk/media/movies:/movies
    restart: unless-stopped