services:
  proxy:
    image: nginx:latest
    container_name: mologhost-proxy
    ports:
      - ":80"
      - ":443"
    links:
      - ghost
    volumes:
      - $PWD/nginx/ghost.molovestoshare.com.crt:/etc/ssl/certs/ghost.molovestoshare.com.crt:z
      - $PWD/nginx/ghost.molovestoshare.com.key:/etc/ssl/private/ghost.molovestoshare.com.pem:z
      - $PWD/nginx/ghost.conf:/etc/nginx/sites-enabled/ghost.conf:z
  ghost:
    image: ghost:latest
    container_name: mologhost-blog
    hostname: ghost
    restart: always
    ports:
      - "2368:2368"
    depends_on:
      - gdb
    environment:
      url: https://ghost.molovestoshare.com/
      database__client: mysql
      database__connection__host: gdb
      database__connection__user: ghost
      database__connection__password: ghostdbpass
      database__connection__database: ghostdb
      comments: false
    volumes:
      - /data/compose/ghost/content:/var/lib/ghost/content
  gdb:
    image: mariadb:latest
    container_name: mologhost-deebee
    hostname: gdb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: your_mysql_root_password
      MYSQL_USER: ghost
      MYSQL_PASSWORD: ghostdbpass
      MYSQL_DATABASE: ghostdb
    expose:
      - "3306"
    volumes:
      - /data/compose/ghost/mariadb:/var/lib/mysql
